name: CI

on:
  workflow_dispatch:
env:
  TZ: Asia/Shanghai
  

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - name: 初始化仓库
        id: init
        run: |
          git clone https://github.com/biliwala/nanopi-openwrt.git
          mydir=$(pwd)
          cd nanopi-openwrt
          dir=$(pwd)
          
      - name: 初始化环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          cd ${{ steps.init.outputs.dir }}
          . 1_initialization_environment.sh
      
      - name: 克隆源码
        run: |
          cd ${{ steps.init.outputs.dir }}
          . 2_clone_source.sh master-v19.07.1 rk3328
          
      - name: 内核打补丁
        run: |
          cd ${{ steps.init.outputs.dir }}
          . patch_kernel_5.4.sh
        
      - name: 打包
        id: assemble_artifact
        run: |
          ls > /tmp/d.txt
          release_tag="test-$(date +%Y-%m-%d-%H%M%S)"
          echo "##[set-output name=release_tag;]$release_tag"
          
      - name: 创建Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.sec_token }}
        with:
          tag_name: ${{ steps.assemble_artifact.outputs.release_tag }}
          release_name: 测试 ${{ steps.assemble_artifact.outputs.release_tag }}
          draft: false
          prerelease: false

      - name: 上传Release附件
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.sec_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /tmp/d.txt
          asset_name: ${{ steps.assemble_artifact.outputs.release_tag }}-test.txt
          #asset_content_type: application/zip
          asset_content_type:	text/plain
          
      - name: 删除旧Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
        with:
          keep_latest: 5
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.sec_token }}
          
